String.toLocaleString({
    
	"en": {
		"%game-intro"           : "Join the ranks and get to be <strong>GENERAL!</strong>",
		"%restart-button"       : "New Game",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Try again",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same rank touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/army\">git.io/army</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-ARMY #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'private',
    '%4'                    : 'corporal',
    '%8'                    : 'sergeant',
    '%16'                   : 'lieutenant',
    '%32'                   : 'captain',
    '%64'                   : 'major',
    '%128'                  : 'colonel',
    '%256'                  : 'brigadier general',
    '%512'                  : 'major general',
    '%1024'                 : 'lieutenant general',
    '%2048'                 : 'general',
		'%s0'                   : 'PVT',
    '%s4'                   : 'CPL',
    '%s8'                   : 'SGT',
    '%s16'                  : 'Lt',
    '%s32'                  : 'CPT',
    '%s64'                  : 'Maj',
    '%s128'                 : 'Col',
    '%s256'                 : 'Brig.Gen',
    '%s512'                 : 'Maj.Gen',
    '%s1024'                : 'Lt.Gen',
    '%s2048'                : 'Gen'
	},
	
	"it": {
		"%game-intro"           : "Unisci i numeri e diventa <strong>Generale!</strong>",
		"%restart-button"       : "Nuova Partita",
		"%keep-playing-button"  : "Continua",
		"%retry-button"         : "Riprova",
		"%game-won"             : "Hai vinto!",
		"%game-over"            : "Hai perso!",
		"%game-explanation"     : "<strong class=\"important\">Come giocare:</strong> Usare i <strong>tasti freccia</strong> per muovere le tessere. Quando due tessere con lo stesso grado si scontrano c&#x27;&egrave; la <strong>promozione!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Nota:</strong> Questo sito <a href=\"http://git.io/army\">git.io/army</a> &egrave; uno spin-off della versione ufficiale di <a href=\"http://git.io/2048\">2048</a> creata da <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%tile-legend"          : "<strong class=\"important\">Legenda Tessere:</strong>",
		"%tweet1"               : "Ho raggiunto il grado di \"",
		"%tweet2"               : "\" a 2048-ARMY #2048game",
		'%2'                    : 'soldato semplice',
    '%4'                    : 'caporale',
    '%8'                    : 'sergente',
    '%16'                   : 'tenente',
    '%32'                   : 'capitano',
    '%64'                   : 'maggiore',
    '%128'                  : 'colonnello',
    '%256'                  : 'brigadiere generale',
    '%512'                  : 'maggiore generale',
    '%1024'                 : 'tenente generale',
    '%2048'                 : 'generale',
		'%s0'                   : 'sol',
    '%s4'                   : 'C.le',
    '%s8'                   : 'SGT',
    '%s16'                  : 'Ten',
    '%s32'                  : 'Cap',
    '%s64'                  : 'Magg',
    '%s128'                 : 'Col',
    '%s256'                 : 'Brig.Gen',
    '%s512'                 : 'Magg.Gen',
    '%s1024'                : 'Ten.Gen',
    '%s2048'                : 'Gen'
	}

});